### ISSUE TITLE
It is not updating sometimes

### ISSUE THREAD

**Issue by istaveren** [PimDoos/kia_connect#5] opened 2022-07-28 06:03 UTC
Some times it doesn't seem to update anymore.

The reload button doesn't fix it. Only restarting homeassistant fixes the issue. 

Will try to find any log records on when this happens.

**Comment by istaveren** [comment] 2022-07-28 10:51
```
2022-07-28 12:48:30 ERROR (MainThread) [homeassistant.util.logging] Exception in update when dispatching 'kia_connect_update_0': ()
Traceback (most recent call last):
  File "/config/custom_components/kia_connect/KiaConnectEntity.py", line 21, in update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 616, in _async_write_ha_state
    if (name := (entry and entry.name) or friendly_name()) is not None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 604, in friendly_name
    return self.name
  File "/config/custom_components/kia_connect/sensor.py", line 175, in name
    return f"{self.vehicle.name} {self._description}"
  File "/config/custom_components/kia_connect/KiaConnectVehicle.py", line 73, in name
    return f"{DEVICE_MANUFACTURER} {self.model}"
  File "/config/custom_components/kia_connect/KiaConnectVehicle.py", line 69, in model
    return self.info["model"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by PimDoos** [comment] 2022-07-28 17:53
If I'd have to guess, I think this is caused by the Kia API not returning user info when the session is already logged in. I have observed this behaviour as well on my instance. I'll do some debugging and see if I can find where this goes wrong.

**Comment by istaveren** [comment] 2022-07-29 21:23
When it is initialized it creates an empty object
```
self.info = {}
```
Later it is used like
```
self.info["model"]
```
Without checking if it is set. 

So consider to initialize it at least with empty data?
```
self.info = { "model" : "", "vin": "", "licensePlate": "", "fuel": ""}
```
Just my two cents on it.

I will try to also debug this, but need to find out first how to do that ;-)

**Comment by PimDoos** [comment] 2022-07-30 14:23
I've spent some time refactoring the integration to run async, and in the process also moved the vehicle_info fetch to the integration init instead of on every update. This should improve reliability.

**Comment by PimDoos** [comment] 2022-07-30 14:39
The changes are now merged, can you update to [v0.1.2](https://github.com/PimDoos/kia_connect/releases/tag/v0.1.2) and let me know if it fixes the issue?

**Comment by istaveren** [comment] 2022-07-31 12:11
Thanks for the update. Now I get.

```
2022-07-31 14:06:38 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/kia_connect/__init__.py", line 59, in update
    await hass.data[DOMAIN][KIA_CONNECT_VEHICLE].update_status()
  File "/config/custom_components/kia_connect/KiaConnectVehicle.py", line 46, in update_status
    raise HomeAssistantError
homeassistant.exceptions.HomeAssistantError
2022-07-31 14:06:38 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/kia_connect/__init__.py", line 59, in update
    await hass.data[DOMAIN][KIA_CONNECT_VEHICLE].update_status()
  File "/config/custom_components/kia_connect/KiaConnectVehicle.py", line 46, in update_status
    raise HomeAssistantError
homeassistant.exceptions.HomeAssistantError
```
But it does seem to fix itself at some point. Will further test it.

**Comment by PimDoos** [comment] 2022-07-31 12:20
When it throws this error at line 46, it means reauthenticating to the API failed. This usually resolves itself, although it should not throw a Task error but rather mark the integration with 'connectivity issues'. I'll have a look into it.

**Comment by PimDoos** [comment] 2022-09-27 16:56
Closing this for now, as I haven't observed these issues on v0.1.3.

**Closed as completed by PimDoos** 2022-09-27 16:56 UTC
